version: '3.7'

networks: 
  java-maven-postgres-network:
    driver: bridge

services:

  java-maven-postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - java-maven-postgres-network

  java-maven-pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=teste@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=teste
    ports:
      - '5050:80'
    depends_on:
      - java-maven-postgresql
    networks:
      - java-maven-postgres-network
